name: 'Cancel Expo EAS Builds'
description: 'Cancel EAS builds that are in queue or in progress'
inputs:
  build_limit:
    description: 'Limit the amount of build to check. Default to the last 10 builds.'
    required: false
    default: '10'
runs:
  using: 'composite'
  steps:
    - id: cancel-eas-builds
      shell: bash
      run: ${{ github.action_path }}/cancel.sh
